/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.3-alpha.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as crons from "../crons.js";
import type * as fetching from "../fetching.js";
import type * as http from "../http.js";
import type * as pages from "../pages.js";
import type * as tasks from "../tasks.js";

import type { ApiFromModules, FunctionReference } from "convex/server";
/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = functions.myModule.myFunction;
 * ```
 */
declare const functions: ApiFromModules<{
  crons: typeof crons;
  fetching: typeof fetching;
  http: typeof http;
  pages: typeof pages;
  tasks: typeof tasks;
}>;
