/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.13.3-alpha.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{}>;
declare const fullApiWithMounts: typeof fullApi & {
  webCrawler: {
    pages: {
      getByDomain: FunctionReference<
        "query",
        "public",
        { domain: string },
        any
      >;
      getByUrl: FunctionReference<"query", "public", { url: string }, any>;
    };
    tasks: {
      get: FunctionReference<"query", "public", {}, any>;
      getRoot: FunctionReference<"query", "public", {}, any>;
      registerTask: FunctionReference<
        "mutation",
        "public",
        { url: string },
        any
      >;
    };
  };
};

export declare const api: FilterApi<
  typeof fullApiWithMounts,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApiWithMounts,
  FunctionReference<any, "internal">
>;
